### PR TITLE
Verifiactions audit, process stats, upgrade 0.19

### PR DESCRIPTION
**Pull request by amiedes**
# What does this PR do?

Incorporates the verifications audit changes from https://github.com/PopulateTools/decidim/pull/1

This includes:

- Include census info in the admin log
- Show more descriptive messages to users, indicating an email hint of the user that has that verification, and admin contact info
- An admin UI to search and destroy existing authorizations
- Upgrade to Decidim 0.19
- Show participation stats for a process in the admin

### CODE REVIEW

**Comment by amiedes** [comment]
My part is deployed to staging. This is how it looks:

**Already verified as a manager user**

Captura de pantalla 2019-10-07 a las 17 00 36

**Already verified as a regular user**

Captura de pantalla 2019-10-07 a las 16 57 52

**Incorrect data / not in census**

Captura de pantalla 2019-10-07 a las 16 32 37

**Admin log**

Captura de pantalla 2019-10-07 a las 16 37 16

@ferblape @entantoencuanto I've set up a small hack in staging because the test webservice is giving timeouts all the time. If you put a document like `12345678#0` it'll use the code after the `#` as the stubbed census code (ej: 0 success, 5 not in census).

**Comment by ferblape** [comment]
@amiedes 

1. update the PR description

2. This person couldn't be authorized because there was another user authorized with the same NIF, but you don't inform about that in the log. I find this confusing:

Screen Shot 2019-10-10 at 10 08 32

**Comment by amiedes** [comment]
New log message:

image

**Comment by amiedes** [comment]
PR description updated

**Pull request merged**
